### PR TITLE
fixed GUI and made it work good lol

### PR DESCRIPTION
**Pull request by Morgandri1**
pretty barebones GUI that ill work on more later

### CODE REVIEW

**Comment by arisu-gh** [comment]
Hey so I was looking through this and there are some issues with the PR.

- The original data2png and png2data scripts were deleted and shoved into a single file. I think they should be kept separate, and possibly made a bit more friendly to import.
- The UI should be using file dialogs instead of having the user paste a full path into a text box. (User friendliness)
- While TK is alright, I would prefer it to use QT eventually.
- These commits remove the command line version of the programs, users shouldn't be forced to use GUI when it isn't totally necessary.
- Your commits are based off of e328daaea534b88a6d0ccfeab99accedaea1f3bd instead of the latest commit 7c03b9cbafa604ddc927d70198ddd56e0eed37a4 , which would make pull requests harder to merge. Please pull changes before making a PR, otherwise it will make me have to resolve conflicts and merge manually, which is never fun.

I do appreciate the PR and am very happy that there is interest in a bit of an old project of mine. I don't mean to sound nit picky or mean or anything like that. I hope you understand :smile:

**Comment by Morgandri1** [comment]
thanks for the feedback

as a python beginner, I was having some trouble keeping the files separate.
on that same note, I don't know how to make a file-browsing system, so any input on that would be appreciated.

I see what you mean with the CLI option, and I agree, so I would be happy to add a second PR to include it.

**Comment by arisu-gh** [comment]
Importing the separate files like you did in your first pull request was good.
Tkinter actually has their own file dialog that you can use https://docs.python.org/3/library/dialog.html
and I'm sure you can find a ton of examples out there to give you a better idea on how to use it.
Perhaps you can keep the app.py as a terminal application, unless it's called with --gui option or something like that.
That way we can keep the program working for terminal usage, keep the original source files separate so it can imported, and then a gui for those who need it.

**Comment by arisu-gh** [comment]
feature added in a25fd738537dfaf0a295446bb21a401a7990857a

**Pull request closed without merging**
